apiVersion: apps/v1
kind: Deployment
metadata:
  name: agent-service
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.agentService.replicas }}
  selector:
    matchLabels:
      app: agent-service
  template:
    metadata:
      labels:
        app: agent-service
    spec:
      containers:
        - name: agent-service
          image: {{ .Values.agentService.image }}
          imagePullPolicy: Never
          ports:
            - containerPort: {{ .Values.agentService.port }}
          env:
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: "kafka:9092"
---
apiVersion: v1
kind: Service
metadata:
  name: agent-service
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: agent-service
  ports:
    - port: {{ .Values.agentService.port }}
      targetPort: {{ .Values.agentService.port }}