apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.kafka.replicas }}
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      initContainers:
        - name: wait-for-zookeeper
          image: busybox
          imagePullPolicy: Never
          command: ['sh', '-c', 'until nc -z zookeeper {{ .Values.zookeeper.port }}; do echo waiting; sleep 2; done']
      containers:
        - name: kafka
          image: {{ .Values.kafka.image }}
          imagePullPolicy: Never
          ports:
            - containerPort: {{ .Values.kafka.port }}
          env:
            - name: KAFKA_BROKER_ID
              value: "1"
            - name: KAFKA_ZOOKEEPER_CONNECT
              value: "zookeeper:{{ .Values.zookeeper.port }}"
            - name: KAFKA_ADVERTISED_LISTENERS
              value: "PLAINTEXT://kafka:{{ .Values.kafka.port }}"
            - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
              value: "1"
            - name: KAFKA_AUTO_CREATE_TOPICS_ENABLE
              value: "true"
---
apiVersion: v1
kind: Service
metadata:
  name: kafka
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: kafka
  ports:
    - port: {{ .Values.kafka.port }}
      targetPort: {{ .Values.kafka.port }}