apiVersion: apps/v1
kind: Deployment
metadata:
  name: zookeeper
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.zookeeper.replicas }}
  selector:
    matchLabels:
      app: zookeeper
  template:
    metadata:
      labels:
        app: zookeeper
    spec:
      containers:
        - name: zookeeper
          image: {{ .Values.zookeeper.image }}
          imagePullPolicy: Never
          ports:
            - containerPort: {{ .Values.zookeeper.port }}
          env:
            - name: ZOOKEEPER_CLIENT_PORT
              value: "{{ .Values.zookeeper.port }}"
---
apiVersion: v1
kind: Service
metadata:
  name: zookeeper
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: zookeeper
  ports:
    - port: {{ .Values.zookeeper.port }}
      targetPort: {{ .Values.zookeeper.port }}