name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: alertflow
          POSTGRES_PASSWORD: alertflow
          POSTGRES_DB: alertflow
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          pip install -r services/alert-service/requirements.txt

      - name: Run tests
        # This ENV section fixes your connection error!
        env:
          DB_HOST: localhost
          DATABASE_URL: postgresql://alertflow:alertflow@localhost:5432/alertflow
        run: |
          cd services/alert-service
          pytest test_alerts.py -v